### ISSUE TITLE
TypeError: prettier.resolveConfig.sync is not a function

### ISSUE THREAD

**Issue by FezVrasta** [prettier/prettier-eslint#124]
**Versions**:

- `prettier-eslint` version: 4.3.2
- `node` version: 8.4.0
- `yarn` version: 1.0.1

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Yes

**Relevant code or config**

```javascript
// @flow
import { stripTrailingSlash, stripLastSegment } from './url-utils';

describe('stripTrailingSlash', () => {
  it('strips one trailing slash', () =>
    expect(stripTrailingSlash('a/b/')).toBe('a/b'));

  it('strips multiple trailing slashes', () =>
    expect(stripTrailingSlash('a/b////')).toBe('a/b'));
});

describe('stripLastSegment', () => {
  it('strips last segment without trailing slash', () =>
    expect(stripLastSegment('a/b')).toBe('a'));

  it('strips last segment with trailing slash', () =>
    expect(stripLastSegment('a/b/')).toBe('a'));
});
```

**What I did:**

```
prettier-eslint --write --single-quote src/utils/url-utils.test.js
```

**What happened:**

```
❯ prettier-eslint --write --single-quote src/utils/url-utils.test.js
prettier-eslint-cli [ERROR]: There was an error formatting "src/utils/url-utils.test.js":
    TypeError: prettier.resolveConfig.sync is not a function
        at getPrettierConfig (/project/node_modules/prettier-eslint/dist/index.js:233:33)
        at format (/project/node_modules/prettier-eslint/dist/index.js:90:51)
        at MapSubscriber.project (/project/node_modules/prettier-eslint-cli/dist/format-files.js:275:55)
        at MapSubscriber._next (/project/node_modules/rxjs/operator/map.js:77:35)
        at MapSubscriber.Subscriber.next (/project/node_modules/rxjs/Subscriber.js:89:18)
        at AsyncSubject.Subject.next (/project/node_modules/rxjs/Subject.js:55:25)
        at AsyncSubject.complete (/project/node_modules/rxjs/AsyncSubject.js:46:35)
        at handlerFn (/project/node_modules/rxjs/observable/BoundNodeCallbackObservable.js:193:33)
        at tryToString (fs.js:513:3)
        at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:501:12)
failure formatting 1 file with prettier-eslint
```

**Problem description:**

When `prettier-eslint` tries to format the file I provided, it throws the above error.
If I use `prettier` directly, it works just fine.

**Suggested solution:**

**Comment by FezVrasta** [comment]
https://github.com/prettier/prettier-eslint-cli/issues/105
