### ISSUE TITLE
Error on Node v4.6.0 

### ISSUE THREAD

**Issue by shardool-freightwalla** [prettier/prettier-eslint#163]
**Versions**:

- `prettier-eslint` version: 8.7.4
- `node` version: 4.6.0
- `npm` (or `yarn`) version: 3.10.10

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Yes || No

**Relevant code or config**

```javascript

```

**What I did:**
prettier-eslint --write <anyFile.js> 

**What happened:**
I am getting the below error on all javascript file.

```
prettier-eslint-cli [ERROR]: There was an error formatting "server/util/mail-util.js":
    TypeError: rulesThatWillNeverBeFixable.includes is not a function
        at /Users/xxx/node_modules/prettier-eslint/dist/utils.js:141:37
        at Array.reduce (native)
        at getRelevantESLintConfig (/Users/ /Users/xxx/node_modules/prettier-eslint/dist/utils.js:136:5
3)
        at getOptionsForFormatting (/Users/xxx/node_modules/prettier-eslint/dist/utils.js:118:1
6)
        at format (/Users/xxx/node_modules/prettier-eslint/dist/index.js:108:62)
        at MapSubscriber.project (/Users/xxx/node_modules/prettier-eslint-cli/dist/format-files.js:305:55)
        at MapSubscriber._next (/Users/xxx/node_modules/rxjs/operators/map.js:79:35)
        at MapSubscriber.Subscriber.next (/Users/xxx/node_modules/rxjs/Subscriber.js:90:18)
        at AsyncSubject.Subject.next (/Users/xxx/node_modules/rxjs/Subject.js:55:25)
        at AsyncSubject.complete (/Users/xxx/node_modules/rxjs/AsyncSubject.js:46:35)
        at handlerFn (/Users/xxx/node_modules/rxjs/observable/BoundNodeCallbackObservable.js:193:33)
        at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```
**Reproduction repository:**

**Problem description:**

**Suggested solution:**
On switching to node version 6.10.3, I am able to run successfully the same command.

**Comment by zimme** [comment]
I'll look at adding this https://www.npmjs.com/package/babel-plugin-array-includes and some other specific babel plugins for the new features instead of using babal-runtime's polyfill.

**Comment by zimme** [comment]
Pretty swamped at work right now, I'll happily review and accept a PR for this.
