### ISSUE TITLE
Can't install prettier-eslint on node 10 & npm 6

### ISSUE THREAD

**Issue by contactjavas** [prettier/prettier-eslint#178]
**Versions**:

- `eslint` version: 4.19.1
- `prettier-eslint` version: 8.8.1
- `node` version: 10.1.0
- `npm` version: 6.1.0
- `platform` version: Windows 10

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Can't install, so can't follow

**Relevant code or config**

```javascript

```

**What I did:**

`npm i -D prettier-eslint` with  `eslint` already installed as *devDependencies*

**What happened:**

I'm getting error when installing `prettier-eslint`:
```
npm ERR! Unexpected end of JSON input while parsing near '...0e149f1898dfa382","ta'
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bagus\AppData\Roaming\npm-cache\_logs\2018-05-26T11_44_41_454Z-debug.log
```

Here is the full log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\bagus\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '-D',
1 verbose cli   'prettier-eslint' ]
2 info using npm@6.1.0
3 info using node@v10.1.0
4 verbose npm-session 715e22c1d5114967
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/prettier-eslint 485ms (from cache)
8 silly fetchPackageMetaData error for prettier-eslint@latest Unexpected end of JSON input while parsing near '...0e149f1898dfa382","ta'
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 1055ms
11 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...0e149f1898dfa382","ta'
11 verbose stack     at JSON.parse (<anonymous>)
11 verbose stack     at parseJson (C:\Users\bagus\AppData\Roaming\npm\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
11 verbose stack     at consumeBody.call.then.buffer (C:\Users\bagus\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\body.js:96:50)
11 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
12 verbose cwd E:\js\test
13 verbose Windows_NT 10.0.17134
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\bagus\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "-D" "prettier-eslint"
15 verbose node v10.1.0
16 verbose npm  v6.1.0
17 error Unexpected end of JSON input while parsing near '...0e149f1898dfa382","ta'
18 verbose exit [ 1, true ]

```

**Reproduction repository:**

**Problem description:**

**Suggested solution:**

**Comment by woodghost** [comment]
Same problem here！
