### ISSUE TITLE
Cannot find module './utils/ast-utils'

### ISSUE THREAD

**Issue by selfagency** [prettier/prettier-eslint#262]
**Versions**:

- `prettier-eslint` version: 9.0.0
- `node` version: 10.17.0
- `npm` (or `yarn`) version: yarn 1.19.1

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Yes

**Relevant code or config**

https://gist.github.com/selfagency/d09dddd361376e47d515a0f1483b03de

**What I did:**

I use `prettier-eslint` via Vetur in VS Code and it's been working just fine up until today, when it started throwing the following error.

**What happened:**
```
[INFO - 8:33:35 AM] Loaded module 'prettier-eslint@undefined' from '/Users/daniel/code/ironmarch/web/node_modules/prettier-eslint/dist/index.js'.
[ERROR - 8:33:35 AM] Error
Cannot find module './utils/ast-utils'
Require stack:
- /Users/daniel/code/ironmarch/web/node_modules/eslint/lib/rules/arrow-spacing.js
- /Users/daniel/code/ironmarch/web/node_modules/eslint/lib/built-in-rules-index.js
- /Users/daniel/code/ironmarch/web/node_modules/eslint/lib/rules.js
- /Users/daniel/code/ironmarch/web/node_modules/eslint/lib/linter.js
- /Users/daniel/code/ironmarch/web/node_modules/eslint/lib/api.js
- /Users/daniel/code/ironmarch/web/node_modules/prettier-eslint/dist/utils.js
- /Users/daniel/code/ironmarch/web/node_modules/prettier-eslint/dist/index.js
- /Users/daniel/.vscode/extensions/esbenp.prettier-vscode-3.6.0/dist/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
```

**Problem description:**

Cannot find module './utils/ast-utils'

**Suggested solution:**
```
¯\_(ツ)_/¯
```

**Comment by skube** [comment]
I have a similar issue — but with react-hooks — which also just recently started acting up and not formatting anything anymore:

```
[INFO - 11:13:13 AM] Loaded module 'prettier-eslint@undefined' from '/Users/skube/client-app/node_modules/prettier-eslint/dist/index.js'.
[ERROR - 11:13:13 AM] Error
Failed to load plugin 'react-hooks' declared in 'CLIOptions': 
Cannot find module 'eslint-plugin-react-hooks'
```

`node`: v10.15.3
`yarn`: 1.19.1
`prettier-eslint`: 9.0.0

**Comment by zimme** [comment]
Please test with `9.0.1` and see if this is still a problem.

**Comment by selfagency** [comment]
Thanks, is it published on `npm`? Because I'm still get 9.0.0.

**Comment by zimme** [comment]
@selfagency Yeah, should be published to npm, https://www.npmjs.com/package/prettier-eslint

**Comment by selfagency** [comment]
Sadly no improvement

```
[INFO - 8:49:52 PM] Loaded module 'prettier@1.19.1' from '/Users/daniel/code/ironmarch/web/node_modules/prettier/index.js'.
[INFO - 8:49:56 PM] Formatting /Users/daniel/code/ironmarch/web/src/main.js.
[INFO - 8:49:56 PM] Loaded module 'prettier@1.19.1' from '/Users/daniel/code/ironmarch/web/node_modules/prettier/index.js'.
[INFO - 8:49:56 PM] Resolved ignore file to /Users/daniel/code/ironmarch/web/.prettierignore.
[INFO - 8:49:56 PM] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
[INFO - 8:49:56 PM] Prettier Options:
{
  "arrowParens": "avoid",
  "bracketSpacing": true,
  "endOfLine": "auto",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": true,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": false,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "none",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "/Users/daniel/code/ironmarch/web/src/main.js",
  "parser": "babel"
}
[INFO - 8:49:56 PM] Loaded module 'prettier-eslint@undefined' from '/Users/daniel/code/ironmarch/web/node_modules/prettier-eslint/dist/index.js'.
[ERROR - 8:49:57 PM] Error
Cannot find module './utils/ast-utils'
Require stack:
- /Users/daniel/code/ironmarch/web/node_modules/eslint/lib/rules/arrow-spacing.js
- /Users/daniel/code/ironmarch/web/node_modules/eslint/lib/built-in-rules-index.js
- /Users/daniel/code/ironmarch/web/node_modules/eslint/lib/rules.js
- /Users/daniel/code/ironmarch/web/node_modules/eslint/lib/linter.js
- /Users/daniel/code/ironmarch/web/node_modules/eslint/lib/api.js
- /Users/daniel/code/ironmarch/web/node_modules/prettier-eslint/dist/utils.js
- /Users/daniel/code/ironmarch/web/node_modules/prettier-eslint/dist/index.js
- /Users/daniel/.vscode/extensions/esbenp.prettier-vscode-3.6.0/dist/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
Error: Cannot find module './utils/ast-utils'
Require stack:
- /Users/daniel/code/ironmarch/web/node_modules/eslint/lib/rules/arrow-spacing.js
- /Users/daniel/code/ironmarch/web/node_modules/eslint/lib/built-in-rules-index.js
- /Users/daniel/code/ironmarch/web/node_modules/eslint/lib/rules.js
- /Users/daniel/code/ironmarch/web/node_modules/eslint/lib/linter.js
- /Users/daniel/code/ironmarch/web/node_modules/eslint/lib/api.js
- /Users/daniel/code/ironmarch/web/node_modules/prettier-eslint/dist/utils.js
- /Users/daniel/code/ironmarch/web/node_modules/prettier-eslint/dist/index.js
- /Users/daniel/.vscode/extensions/esbenp.prettier-vscode-3.6.0/dist/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:796:719)
    at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:765:302)
    at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:761:870)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:524)
    at Object.<anonymous> (/Users/daniel/code/ironmarch/web/node_modules/eslint/lib/rules/arrow-spacing.js:11:18)
    at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:749)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:796:719)
    at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:765:302)
    at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:761:870)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:524)
    at Object.<anonymous> (/Users/daniel/code/ironmarch/web/node_modules/eslint/lib/built-in-rules-index.js:19:22)
    at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:749)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:796:719)
    at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:765:302)
    at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:761:870)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:524)
    at Object.<anonymous> (/Users/daniel/code/ironmarch/web/node_modules/eslint/lib/rules.js:14:22)
    at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:749)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:796:719)
    at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:765:302)
    at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:761:870)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:524)
    at Object.<anonymous> (/Users/daniel/code/ironmarch/web/node_modules/eslint/lib/linter.js:26:13)
    at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:749)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:796:719)
    at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:765:302)
    at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:761:870)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:524)
    at Object.<anonymous> (/Users/daniel/code/ironmarch/web/node_modules/eslint/lib/api.js:8:16)
    at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:749)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:796:719)
    at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:765:302)
    at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:761:870)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:524)
    at requireModule (/Users/daniel/code/ironmarch/web/node_modules/prettier-eslint/dist/utils.js:387:12)
    at getESLintCLIEngine (/Users/daniel/code/ironmarch/web/node_modules/prettier-eslint/dist/utils.js:400:7)
    at getESLintConfig (/Users/daniel/code/ironmarch/web/node_modules/prettier-eslint/dist/index.js:210:51)
    at format (/Users/daniel/code/ironmarch/web/node_modules/prettier-eslint/dist/index.js:75:71)
    at /Users/daniel/.vscode/extensions/esbenp.prettier-vscode-3.6.0/src/PrettierEditService.ts:281:40
    at t.default.safeExecution (/Users/daniel/.vscode/extensions/esbenp.prettier-vscode-3.6.0/src/PrettierEditService.ts:343:27)
    at t.default.<anonymous> (/Users/daniel/.vscode/extensions/esbenp.prettier-vscode-3.6.0/src/PrettierEditService.ts:280:21)
    at Generator.next (<anonymous>)
    at s (/Users/daniel/.vscode/extensions/esbenp.prettier-vscode-3.6.0/dist/extension.js:1:347738)
[INFO - 8:49:57 PM] Formatting completed in 788.530894ms.
```

**Comment by skube** [comment]
This fixed my issue:
https://www.stephencharlesweiss.com/2019-10-14/eslint-prettier-vscode/

**Comment by DeviousM** [comment]
Problem still prevails with newest version of VS Code. Tried reinstalling everything and while trying to format JS file this happens:

`["INFO" - 5:12:03 PM] Formatting /Users/michal/Projects/project/myfile.js
["INFO" - 5:12:03 PM] Using ignore file (if present) at /Users/michal/Projects/project/.prettierignore
["INFO" - 5:12:03 PM] Loaded module 'prettier@1.19.1' from '/Users/michal/Projects/project/node_modules/prettier/index.js'
["INFO" - 5:12:03 PM] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 5:12:03 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 5:12:03 PM] Prettier Options:
{
  "filepath": "/Users/michal/Projects/project/apps/stonly-editor/Site/Webapp/General/Sections/UserSettings/Settings/Billing/Billing.js",
  "parser": "babel",
  "useTabs": false,
  "tabWidth": 2,
  "endOfLine": "lf",
  "printWidth": 120,
  "bracketSpacing": true,
  "htmlWhitespaceSensitivity": "css",
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "singleQuote": true,
  "trailingComma": "es5"
}
["INFO" - 5:12:03 PM] Loaded module 'prettier-eslint@unknown' from '/Users/michal/Projects/project/node_modules/prettier-eslint/dist/index.js'
["INFO" - 5:12:03 PM] Formatting using 'prettier-eslint'
["ERROR" - 5:12:03 PM] Error formatting document.
["ERROR" - 5:12:03 PM] Cannot find module '../util/ast-utils'
Require stack:
- /Users/michal/Projects/project/node_modules/eslint/lib/rules/arrow-spacing.js
- /Users/michal/Projects/project/node_modules/eslint/lib/rules/index.js
- /Users/michal/Projects/project/node_modules/eslint/lib/shared/config-validator.js
- /Users/michal/Projects/project/node_modules/eslint/lib/linter/linter.js
- /Users/michal/Projects/project/node_modules/eslint/lib/linter/index.js
- /Users/michal/Projects/project/node_modules/eslint/lib/cli-engine/cli-engine.js
- /Users/michal/Projects/project/node_modules/eslint/lib/cli-engine/index.js
- /Users/michal/Projects/project/node_modules/eslint/lib/api.js
- /Users/michal/Projects/project/node_modules/prettier-eslint/dist/utils.js
- /Users/michal/Projects/project/node_modules/prettier-eslint/dist/index.js
- /Users/michal/.vscode/extensions/esbenp.prettier-vscode-3.20.0/dist/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
Error: Cannot find module '../util/ast-utils'
Require stack:
- /Users/michal/Projects/project/node_modules/eslint/lib/rules/arrow-spacing.js
- /Users/michal/Projects/project/node_modules/eslint/lib/rules/index.js
- /Users/michal/Projects/project/node_modules/eslint/lib/shared/config-validator.js
- /Users/michal/Projects/project/node_modules/eslint/lib/linter/linter.js
- /Users/michal/Projects/project/node_modules/eslint/lib/linter/index.js
- /Users/michal/Projects/project/node_modules/eslint/lib/cli-engine/cli-engine.js
- /Users/michal/Projects/project/node_modules/eslint/lib/cli-engine/index.js
- /Users/michal/Projects/project/node_modules/eslint/lib/api.js
- /Users/michal/Projects/project/node_modules/prettier-eslint/dist/utils.js
- /Users/michal/Projects/project/node_modules/prettier-eslint/dist/index.js
- /Users/michal/.vscode/extensions/esbenp.prettier-vscode-3.20.0/dist/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
	at Function.Module._load (internal/modules/cjs/loader.js:531:27)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:837:268)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:807:106)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:803:550)
	at Module.require (internal/modules/cjs/loader.js:685:19)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:524)
	at Object.<anonymous> (/Users/michal/Projects/project/node_modules/eslint/lib/rules/arrow-spacing.js:11:18)
	at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
	at Module.load (internal/modules/cjs/loader.js:645:32)
	at Function.Module._load (internal/modules/cjs/loader.js:560:12)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:837:268)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:807:106)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:803:550)
	at Module.require (internal/modules/cjs/loader.js:685:19)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:524)
	at arrow-spacing (/Users/michal/Projects/project/node_modules/eslint/lib/rules/index.js:22:28)
	at Map.entries (/Users/michal/Projects/project/node_modules/eslint/lib/rules/utils/lazy-loading-rule-map.js:87:28)
	at entries.next (<anonymous>)
	at /Users/michal/Projects/project/node_modules/eslint/lib/cli-engine/cli-engine.js:629:13
	at Generator.next (<anonymous>)
	at new Map (<anonymous>)
	at CLIEngine.getRules (/Users/michal/Projects/project/node_modules/eslint/lib/cli-engine/cli-engine.js:628:16)
	at getRelevantESLintConfig (/Users/michal/Projects/project/node_modules/prettier-eslint/dist/utils.js:95:55)
	at getOptionsForFormatting (/Users/michal/Projects/project/node_modules/prettier-eslint/dist/utils.js:83:18)
	at format (/Users/michal/Projects/project/node_modules/prettier-eslint/dist/index.js:84:64)
	at /Users/michal/.vscode/extensions/esbenp.prettier-vscode-3.20.0/dist/extension.js:1:350580
	at t.default.safeExecution (/Users/michal/.vscode/extensions/esbenp.prettier-vscode-3.20.0/dist/extension.js:1:351254)
	at t.default.<anonymous> (/Users/michal/.vscode/extensions/esbenp.prettier-vscode-3.20.0/dist/extension.js:1:350554)
	at Generator.next (<anonymous>)
	at s (/Users/michal/.vscode/extensions/esbenp.prettier-vscode-3.20.0/dist/extension.js:1:345019)
["INFO" - 5:12:03 PM] Formatting completed in 38.49938ms.`

**Comment by reduardo7** [comment]
Why it is closed? Still not working!

**Comment by xieww-aries** [comment]
I got the same issue, but i think mostly because the newest version of eslint.
```js
Error: Cannot find module 'eslint/lib/rules/utils/ast-utils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/xieww/Desktop/CRN/FlightCharterPlane/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-unused-vars.js:24:21)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

**Comment by mehradrishty** [comment]
> I got the same issue, but i think mostly because the newest version of eslint.
> 
> ```js
> Error: Cannot find module 'eslint/lib/rules/utils/ast-utils'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:508:25)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at Object.<anonymous> (/Users/xieww/Desktop/CRN/FlightCharterPlane/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-unused-vars.js:24:21)
>     at Module._compile (internal/modules/cjs/loader.js:701:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
>     at Module.load (internal/modules/cjs/loader.js:600:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
> ```

I am getting the same error.

**Comment by shinter61** [comment]
I fixed by `yarn add --dev eslint`

**Comment by victoriatomzik** [comment]
Same:
```
Error: Cannot find module 'eslint/lib/rules/utils/ast-utils'
Require stack:
- /Users/xxx/Projects/ui/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-unused-vars.js
- /Users/xxx/Projects/ui/node_modules/@typescript-eslint/eslint-plugin/dist/rules/index.js
- /Users/xxx/Projects/ui/node_modules/@typescript-eslint/eslint-plugin/dist/index.js
- /Users/xxx/Projects/ui/node_modules/eslint/lib/config/plugins.js
- /Users/xxx/Projects/ui/node_modules/eslint/lib/config.js
- /Users/xxx/Projects/ui/node_modules/eslint/lib/cli-engine.js
- /Users/xxx/Projects/ui/node_modules/eslint/lib/cli.js
- /Users/xxx/Projects/ui/node_modules/eslint/bin/eslint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/xxx/Projects/ui/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-unused-vars.js:24:21)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
```

**Comment by noisy** [comment]
@victoriatomzik just started getting this error too. Maybe this is something new? Like, package become broken

**Comment by EricRabil** [comment]
I believe @victoriatomzik's issue was related to typescript-eslint not supporting ESLint 5. https://github.com/typescript-eslint/typescript-eslint/pull/2917 was recently merged which fixes this.

**Comment by nomi9995** [comment]
I am getting this error
```
'Cannot find module '/Users/apple/Downloads/react-native-component-splitter/node_modules/eslint/lib/api.j`
```
