### ISSUE TITLE
Cannot find module 'core-js/modules/es.array.iterator'

### ISSUE THREAD

**Issue by grit96** [prettier/prettier-eslint#348]
**Versions**:

- `prettier-eslint` version: 10.1.1
- `node` version: 12.4.0
- `npm` version: 6.9.0

**What I did:**

Ran `prettier-eslint` in vscode using `prettier-vscode`.

**What happened:**

```
["ERROR" - 2:35:24 PM] Error loading node module '/Users/geraintwhite/repos/work/newteam/cloud-voice-app/node_modules/prettier-eslint/dist/index.js'
["ERROR" - 2:35:24 PM] Cannot find module 'core-js/modules/es.array.iterator'
Require stack:
- /Users/geraintwhite/repos/work/newteam/cloud-voice-app/node_modules/prettier-eslint/dist/index.js
- /Users/geraintwhite/.vscode/extensions/esbenp.prettier-vscode-4.7.0/dist/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
Error: Cannot find module 'core-js/modules/es.array.iterator'
Require stack:
- /Users/geraintwhite/repos/work/newteam/cloud-voice-app/node_modules/prettier-eslint/dist/index.js
- /Users/geraintwhite/.vscode/extensions/esbenp.prettier-vscode-4.7.0/dist/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
	at Module._load (internal/modules/cjs/loader.js:622:27)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:955:769)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:925:106)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:524)
	at Object.<anonymous> (/Users/geraintwhite/repos/work/newteam/cloud-voice-app/node_modules/prettier-eslint/dist/index.js:3:1)
	at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
	at Module.load (internal/modules/cjs/loader.js:735:32)
	at Module._load (internal/modules/cjs/loader.js:648:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:955:769)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:925:106)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:524)
	at t.ModuleResolver.loadNodeModule (/Users/geraintwhite/.vscode/extensions/esbenp.prettier-vscode-4.7.0/dist/extension.js:1:30473)
	at t.ModuleResolver.requireLocalPkg (/Users/geraintwhite/.vscode/extensions/esbenp.prettier-vscode-4.7.0/dist/extension.js:1:29216)
	at t.ModuleResolver.getModuleInstance (/Users/geraintwhite/.vscode/extensions/esbenp.prettier-vscode-4.7.0/dist/extension.js:1:28566)
	at t.default.<anonymous> (/Users/geraintwhite/.vscode/extensions/esbenp.prettier-vscode-4.7.0/dist/extension.js:1:59538)
	at Generator.next (<anonymous>)
	at s (/Users/geraintwhite/.vscode/extensions/esbenp.prettier-vscode-4.7.0/dist/extension.js:1:53984)
["ERROR" - 2:35:24 PM] Failed to load local module prettier-eslint.
["ERROR" - 2:35:24 PM] Cannot read property 'version' of undefined
TypeError: Cannot read property 'version' of undefined
	at t.ModuleResolver.requireLocalPkg (/Users/geraintwhite/.vscode/extensions/esbenp.prettier-vscode-4.7.0/dist/extension.js:1:29370)
	at t.ModuleResolver.getModuleInstance (/Users/geraintwhite/.vscode/extensions/esbenp.prettier-vscode-4.7.0/dist/extension.js:1:28566)
	at t.default.<anonymous> (/Users/geraintwhite/.vscode/extensions/esbenp.prettier-vscode-4.7.0/dist/extension.js:1:59538)
	at Generator.next (<anonymous>)
	at s (/Users/geraintwhite/.vscode/extensions/esbenp.prettier-vscode-4.7.0/dist/extension.js:1:53984)
["INFO" - 2:35:25 PM] Formatting completed in 102.549735ms.
```

**Problem description:**

Looks like it was caused by this commit when `core-js` was removed from dependencies: 29e9d1e2bb3aa24872cb3b631ba44274da45efe8.

**Suggested solution:**

Should be resolved by re-adding `core-js` to dependencies.

**Comment by esetnik** [comment]
I opened #359 which should fix this issue.

**Comment by exah** [comment]
Please re-open, PR not merged yet :)
