### ISSUE TITLE
Only Prettier (but not ESLint) formatting is applied to `.cjs` files

### ISSUE THREAD

**Issue by mxxk** [prettier/prettier-eslint#830]
**Versions**:

- `prettier-eslint` version: 7.1.0
- `node` version: v18.12.1
- `npm` (or `yarn`) version: 8.19.2

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Yes

**Relevant code or config**

`example.cjs`:

```js
module.exports = '\'none\'';`
```

`example.js`:

```js
export default '\'none\'';
```

**What I did:**

- Configured Prettier and ESLint to format strings using single quotes.
- Put the same literal string into `example.js` and `example.cjs`—`'\'none\''`.
- Ran `prettier-eslint --write` to format both files.
- Ran `eslint .` to assert that the formatted files still comply with ESLint rules.

**What happened:**

- `prettier-eslint` left the string `'\'none\''` in `example.js` as-is (expected).
- However, `prettier-eslint` reformatted the same string in `example.cjs` to `"'none'"` (unexpected).
- Subsequently, `eslint` failed on `example.cjs` due to the double-quoted string.

```
$ npx prettier-eslint example.cjs example.js --write
success formatting 1 file with prettier-eslint
1 file was unchanged
```

```
$ npx eslint example.cjs example.js

/repo/example.cjs
  1:16  error  Strings must use singlequote  quotes

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

**Reproduction repository:**

https://github.com/mxxk-examples/prettier-eslint-issue-830

**Problem description:**

Though `prettier-eslint` is expected to not make any formatting changes to either file, it reformats `example.cjs` with a double-quoted string. This is inconsistent with ESLint configuration, which makes me suspect that only Prettier formatting is being applied to that file.

**Aside 1: When Prettier and ESLint are run separately, the end result is correct**

Since `prettier-eslint` describes itself as

> Formats your JavaScript using [`prettier`](https://github.com/jlongster/prettier) followed by [`eslint --fix`](http://eslint.org/)

I ran Prettier and ESLint separately to see what would happen. Interestingly, this _does_ produce the expected result:

1. Run Prettier:

    ```
    $ npx prettier --write example.cjs example.js
    example.cjs 22ms
    example.js 2ms
    ```

    At this point, both files are reformatted to contain `"'none'"`, which is expected according to https://prettier.io/docs/en/options.html#quotes:
    
    > - If the number of quotes outweighs the other quote, the quote which is less used will be used to format the string - Example: `"I'm double quoted"` results in `"I'm double quoted"` and `"This \"example\" is single quoted"` results in `'This "example" is single quoted'`.

2. Run ESLint:

    ```
    $ npx eslint --fix example.cjs example.js
    ```

    ESLint reformats both files back to `'\'none\''` to comply with the ESLint rule `quotes: ['error', 'single']`.

**Aside 2: ESLint appears to ignore `.cjs` files when run with `.`**

When ESLint is run with `.` as the target directory, it appears to completely ignore `example.cjs` (due to the extension, I'm guessing):

```
$ npx prettier --write example.cjs example.js
example.cjs 22ms
example.js 2ms
```

```
$ npx eslint .

/repo/example.js
  1:16  error  Strings must use singlequote  quotes

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

```

The above output only flagged one problem with `example.js`, but not `example.cjs`:

```
$ npx eslint example.cjs

/repo/example.cjs
  1:18  error  Strings must use singlequote  quotes

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

Perhaps it is this discrepancy in ESLint which is causing this formatting problem to surface in `prettier-eslint`, despite the explicit files being mentioned in the command-line (`example.cjs`, `example.js`).

**Comment by mxxk** [comment]
No issue activity due to lack of response from maintainers

**Comment by mxxk** [comment]
Nope, not completed. Please reopen.

**Comment by mxxk** [comment]
This is still an issue, so mentioning @idahogurl @JounQin for visibility

**Comment by idahogurl** [comment]
@mxxk Try putting this in your ESLint config 
```
extensions: '[.js',
    '.jsx',
    '.ts',
    '.tsx',
    '.cjs',
    '.mjs',
    '.vue']
```

**Comment by mxxk** [comment]
Thanks @idahogurl, but if I understood your suggestion correctly, `extensions` is not a valid top-level property in ESLint config (`.eslintrc.*`). Using the repro example above,

```
$ npx eslint example.cjs example.js

Oops! Something went wrong! :(

ESLint: 8.31.0

Error: ESLint configuration in .eslintrc.cjs is invalid:
	- Unexpected top-level property "extensions".

    at ConfigValidator.validateConfigSchema (/repo/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2156:19)
    at ConfigArrayFactory._normalizeConfigData (/repo/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2998:19)
    at ConfigArrayFactory.loadInDirectory (/repo/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2866:33)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/repo/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3848:46)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/repo/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3769:18)
    at FileEnumerator._iterateFilesWithFile (/repo/node_modules/eslint/lib/cli-engine/file-enumerator.js:368:43)
    at FileEnumerator._iterateFiles (/repo/node_modules/eslint/lib/cli-engine/file-enumerator.js:349:25)
    at FileEnumerator.iterateFiles (/repo/node_modules/eslint/lib/cli-engine/file-enumerator.js:299:59)
    at iterateFiles.next (<anonymous>)
    at CLIEngine.executeOnFiles (/repo/node_modules/eslint/lib/cli-engine/cli-engine.js:786:48)
```

Digging a little more, according to https://github.com/eslint/eslint/issues/1674, https://github.com/eslint/eslint/issues/2274, and https://github.com/eslint/eslint/issues/10828, ESLint does not support a config file equivalent to passing `--ext` to the ESLint CLI.

**Comment by idahogurl** [comment]
@
